#ifndef CPP_DOCKER_ISOLATION_PROVIDER_DEEPCLIENTCPPWRAPPER_H
#define CPP_DOCKER_ISOLATION_PROVIDER_DEEPCLIENTCPPWRAPPER_H


class DeepClientCppWrapper {

};


#endif //CPP_DOCKER_ISOLATION_PROVIDER_DEEPCLIENTCPPWRAPPER_H
